---
name: Run OXO Tournament

on:
  workflow_dispatch:

jobs:
  oxo-tournament:
    name: Play oxo Tournament
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup python environment
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt

      # Run tournament code
      - name: Run Tournament
        run: |
          python example.py

      # Save the tournament results as an artefact
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v3
      #     with:
      #       name: oxo_results
      #       path: oxo_results.txt
